[[commands]]
keyboard = "VID_046D&PID_C52B"
cmd = "powershell.exe"
args = [ "-ExecutionPolicy", "Bypass", "-File", "resources\\tv.ps1" ]

[[commands]]
keyboard = ""
cmd = "powershell.exe"
args = [ "-ExecutionPolicy", "Bypass", "-File", "Resources\\normal.ps1" ]